### ISSUE TITLE
Unable to download or offline use

### ISSUE THREAD

**Issue by MeapVR** [austinried/subtracks#104]
Hello,

Just wanted to say I'm loving the app so far.
For some reason however the download for offline use button is greyed out. Is this not a feature yet? Or is the app not working properly for just me.

I am on a Samsung Galaxy S22 Ultra.

Thanks in advance,

**Comment by austinried** [comment]
It's not implemented yet, I'm working towards it though 🙂

Duplicate of #3

**Comment by MeapVR** [comment]
Cool, sounds good. I am hyped for this as your app has the best UI and responsiveness in my opinion. Are you planning on adding support for casting and DLNA in the future?

**Comment by austinried** [comment]
Most likely yes, I have to do some figuring out related to publishing on F-Droid still if I have to take a dependency on Google code for casting though.

**Comment by MeapVR** [comment]
I think ultimately more people use DLNA rather than a chrome cast. I myself at least am looking forward to DLNA so I can easily control my KEF LSX Speakers. I'm doing it through bluetooth currently which can be a pain as bluetooth grabs all audio of the phone instead of just the music.

Thanks for the answers!

Also a sidenote, I found a bug.

I use this app for my Navidrome server and if I try to load my playlist with about 400 songs it freezes/crashes the app when attempting to load the song images. Thought I'd let you know.

**Comment by austinried** [comment]
Are you on the latest version? (1.2.0) I made some changes in how that would be loaded recently so I'm curious if that's causing the problem or improves it for you if you're on an older version.

**Comment by MeapVR** [comment]
I am on version 1.2.0

**Comment by austinried** [comment]
Gotcha, if you could create a separate issue with details on that I'd appreciate it.

**Comment by MeapVR** [comment]
Sure, will do. I will take a video soon which shows the issue.
