### ISSUE TITLE
[Feature] More shuffle play modes

### ISSUE THREAD

**Issue by austinried** [austinried/subtracks#11]
Would be great to be able to just hit shuffle and get all random songs from across the library, or a genre, or an artist, etc.

**Comment by 0xv31an5a1i5** [comment]
Implementation of this feature will make me use subtracks officially and not use Navidrome web UI as I use Shuffle a lot to discover new songs across the library.

**Comment by emes81** [comment]
I would also like to add a voice for this - especially a mode for shuffle all songs from the entire library!

**Comment by sjiawjbssj** [comment]
Is there an ETA for this? Based on the to-do list of the PR (#67) the only thing missing is a waiting animation.

**Comment by austinried** [comment]
Added in 2.0.0 via radio play mode for entire library (on the Browse page), artists, and shuffle on the genre page.
