### ISSUE TITLE
Keeps crashing when using ampache server

### ISSUE THREAD

**Issue by izyspania** [austinried/subtracks#119]
The app keeps crashing in emulator when im using it with Ampache server. https://demo.amapche.dev demo/demodemo
I am getting the error below but it crashes even without it showing. It seems to work better with navidrome (no errors) but it still crashing at some point. Its crashing faster if im scrolling the playlists.
 Installed subtracks from playstore and it still crashing in emulator. Seem not to crash on my phone (android 11) but in emulator its always cashing (even if im using the playstore app or if im building it myself from the source). Last version didnt had this problem. After some digging it seem that downloading images causes this error but i am not sure.

WARN  [Error: Request does not satisfy expected content type. Expected: image Actual: text] (only on ampache)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android 9 (same with 8 )
 - Subtracks version 1.3.0
Installing APK 'app-debug.apk' on 'Pixel_4_API_28(AVD) - 9' for app:debug

**Comment by austinried** [comment]
That warning shouldn't cause a crash as far as I can tell, it's just saying that the image fetch failed because ampache responded with text (probably an XML error) instead of an image.

I haven't been able to duplicate this in the release or debug builds in my emulator.  Can you hook up Flipper or something similar to get device logs and see if there is a stack trace or something that shows up there?

**Comment by izyspania** [comment]
From Flipper ( self build from source ):

FATAL EXCEPTION: mqt_native_modules
Process: com.subtracks, PID: 10743
java.lang.ArithmeticException: divide by zero
	at com.ReactNativeBlobUtil.ReactNativeBlobUtilReq$1.handleMessage(ReactNativeBlobUtilReq.java:200)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:923)

**Comment by austinried** [comment]
> java.lang.ArithmeticException: divide by zero
at com.ReactNativeBlobUtil.ReactNativeBlobUtilReq$1.handleMessage(ReactNativeBlobUtilReq.java:200)

Is that the one that pops up in the Crash Reporter in Flipper?  I could see how that one might cause a crash, and it looks like that's an area of the code I recently touched to add progress reporting from the Android Download Manager in the React Native Blob Util package.  Weird that it only happens for Ampache, I guess the server is just set up to report a 0 byte file size sometimes.  That area of the code should not attempt to divide by zero in any case so I'll put in a PR over there for it.

**Comment by izyspania** [comment]
Yes , thats what i get with Crash Reporter in Flipper, it does the same with Navidrome too but rare and it takes more time till i get the crash , with Ampache i cant use the app more than 20 - 30 secs.

**Comment by izyspania** [comment]
I saw your pull request and i changed that line with your fix and it works perfect (so far).

**Comment by austinried** [comment]
Great to hear, I'll plan on using my own `subtracks` branch of my fork over there in the next release if it doesn't get merged/released soon.
