### ISSUE TITLE
Russian translation is imperfect

### ISSUE THREAD

**Issue by justmax437** [austinried/subtracks#121]
**Describe the bug**
Some strings in the app are translated to russian in such a manner they are not used in regular day-to-day language, cases are sometimes wrong.

For example, under the Library tab there is "Albums", "Artists", and "Playlists" tabs, which are displayed as "Альбома", "Исполнителя" and "Плейлиста", the cases are wrong here, it should be "Альбомы", "Исполнители", "Плейлисты". There are more of such mistakes, i cannot compile full list right now, but i'm willing to provide right translations where applicable if this is important enough to even bother.

**Screenshots**

Library tab in russian

![photo_2022-05-04_12-22-33](https://user-images.githubusercontent.com/5184586/166654863-cbdbbd7e-ffeb-4655-8809-f6ede4e561a3.jpg)

Accurate translation in Stellio Player

![photo_2022-05-04_12-24-38](https://user-images.githubusercontent.com/5184586/166655196-50c067b2-214f-46fd-85c2-9761f5ef0cf9.jpg)

**Comment by austinried** [comment]
Thanks for finding this, I don't speak Russian unfortunately so I rely on volunteers to translate these strings from the Subtracks project on Weblate: https://hosted.weblate.org/projects/subtracks/subtracks/

If you're able to correct those there they will be pushed into the project automatically and then I can include them in the next release!
