### ISSUE TITLE
Allow for > 300s buffer

### ISSUE THREAD

**Issue by AvverbioPronome** [austinried/subtracks#122]
**Is your feature request related to a problem? Please describe.**
I am often on trains and roads where I can have no connectivity or bad connectivity for a longish time. 

**Describe the solution you'd like**
I'd like to set the maximum buffer to 1800s (half an hour) or more.

**Describe alternatives you've considered**
Other clients?

**Additional context**
None

**Comment by austinried** [comment]
I would think this use case should be covered better by #3.  The buffer has the potential to get reset (changing songs, etc) and is meant for evening out spotty connections, it's more fragile for long dropouts in connectivity.  With offline cached songs though you'll be able to start/stop/resume them all without connection.
