### ISSUE TITLE
add an "add to queue" function 

### ISSUE THREAD

**Issue by AvverbioPronome** [austinried/subtracks#123]
**Is your feature request related to a problem? Please describe.**
I wanted to stream two albums in succession.

**Describe the solution you'd like**
A functionality that lets me tell the app what tracks to play after the current album

**Describe alternatives you've considered**
Other clients?

**Additional context**
None

**Comment by Vista2003** [comment]
To add to this, have both a play next and add to queue buttons to it for both singles and albums. Once it's in there, I think Subtracks would be my go to client.

**Comment by austinried** [comment]
Tracking this in #9. I'm currently working on support for this in either 1.4.0 or 1.5.0, not sure which it will land in yet.
