### ISSUE TITLE
Scrolling deceleration is not working

### ISSUE THREAD

**Issue by vfosnar** [austinried/subtracks#124]
**Describe the bug**
When stopped scrolling the animation does not properly decelerate and stops instantly

**To Reproduce**
1. Open the app, scrolling animation works just fine on the home screen
2. Click on "Library" or "Search" tab, the scrolling animation is now broken
3. Clicking back on "Home" tab does not fix it

**Expected behavior**
Scrolling should slowly decelerate

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 7
 - OS: Android 12
 - Subtracks version: 1.3.0.9 (F-Droid)

**Comment by vfosnar** [comment]
Got rid of this issue by installing another ROM. Also this looks more like React Native issue but the weird thing is other React Native apps worked just fine.

**Comment by austinried** [comment]
Very strange, I tried a few different phones and wasn't able to repro this but let me know if it resurfaces and we can reopen.
