### ISSUE TITLE
Turkish Language support

### ISSUE THREAD

**Issue by murtezayesil** [austinried/subtracks#126]
I am working on Turkish Language support on weblate and had few things to say or ask:
1. I didn't really get the idea behind scrobbing. Does app prioritize songs according to their play frequency? Or is it more like "who listened to this also listened to that" kind of recommendation system?
I skipped all the strings with "scrobble" for now. (settings.music.options.scrobble.title).
3. Ping me whenever strings for future features in development such as "Download" or "Customize Home" are available for translation.
4. I am trying to translate according to the context which is probably why we cannot let all translation be done by computers just yet. Expect translations such as "Show all results ..." rather than "More ..."

**Comment by austinried** [comment]
Thanks for you help on this, always appreciate having a new language added.

> I didn't really get the idea behind scrobbing.

It's a word that I think was actually made up by Last.fm some 20 years ago, and it's meant to be like "blogging" but for the songs that you're listening to.  So to say you "scrobble" a song means you send that song/artist info to a server and then that server tracks what you've listened to.  In the case of Subsonic servers, they take that scrobble and increase the play count for the song, and optionally many can then forward the scrobble to Last.fm or other services that people like to keep track of those things on.  It isn't really used for much though besides that play count for our purposes, and the Subsonic servers don't really do much suggestion or anything based on that.

> Ping me whenever strings for future features in development such as "Download" or "Customize Home" are available for translation.

Can do, thank you for volunteering!

> I am trying to translate according to the context which is probably why we cannot let all translation be done by computers just yet. Expect translations such as "Show all results ..." rather than "More ..."

That's totally fine and appreciated, cause yeah I expect that while "More..." might make sense with context in English on a certain screen, a direct translation into another language might not!

**Comment by austinried** [comment]
Closing this with #125 but let me know if there's any other questions.
