### ISSUE TITLE
Limit height of playlist description

### ISSUE THREAD

**Issue by metalheim** [austinried/subtracks#127]
**My problem**
I have playlists with a long description. 
When viewing the playlist-list page (where all your playlists are shown), the looong descriptions cause the layout to look very ugly.

**Describe the solution you'd like**
Only show the maximum X characters of the playlist description when in the playlist-list.

**Describe alternatives you've considered**
Limit the height of the container element of the playlist-description and disable overflow (maybe even with text-overflow:ellipsis to indicate that its overflowing)

**Additional context**
A screenshot:
![Screenshot_20220528-160814](https://user-images.githubusercontent.com/44159957/170828999-a957b81e-b9af-4c4d-9cbc-3c658cf90849.png)

**Comment by austinried** [comment]
Hopefully this will be a quick resolve with the next version I'm working on, as I'm already working on making almost all of these list views like this have a set height for their items which increases their performance quite a bit.

**Comment by austinried** [comment]
Fixed in 2.0.0
