### ISSUE TITLE
Filesystem Sorting

### ISSUE THREAD

**Issue by kyagloski** [austinried/subtracks#128]
Use filesystem directories for displaying music rather than id3 tags. Something like this would look like, for example, if I had a directory with flac files and another with mp3 both respectively named flac and mp3, I would see a list of those two directories, I click on one, it brings me into that directory, then I can see all the subdirectories. Eventually you'd get to your music files where they can be played. If files like cover.png or jpg etc exist in a directory they would be used as the images representing the directory. This feature would be similar to how subsonic is implemented when sort by id3 tags is turned off.

**Comment by austinried** [comment]
Tracking this in #5 currently, thank you for the details on use case here though.
