### ISSUE TITLE
Casting devices not found/listed

### ISSUE THREAD

**Issue by skyzem** [austinried/subtracks#13]
First of all - Great work!

I found out that Subtracks does not recognize my cast devices (chormecast) - dSub does.

I am no developer, so I don't know how to contribute more precise information. Please assist, if needed.

best and thank you very much!

![Screenshot_20210902-160542_Subtracks](https://user-images.githubusercontent.com/5577218/131859968-8e3fa9b3-311e-4d45-8343-c6e79a6141db.jpg)

**Comment by austinried** [comment]
That's my bad, I added that button during prototyping and later found out that casting wasn't fully supported in the audio library I'm using right now, and that I also may need to add non-free Google libraries to get that to work which would cause issues with the F-Droid build.

So as of right now casting is not supported.  I'll remove that button from the interface to clear up confusion.

**Comment by austinried** [comment]
That's my bad, I added that button during prototyping and later found out that casting wasn't fully supported in the audio library I'm using right now, and that I also may need to add non-free Google libraries to get that to work which would cause issues with the F-Droid build.

So as of right now casting is not supported.  I'll remove that button from the interface to clear up confusion.

**Comment by eugenialoli** [comment]
I wonder if you could have two different builds, for play store, and f-droid. You see, the reason why I'd use a subsonic client is to cast it into our hi-fi system. I never listen music via the phone itself. We have an audio chromecast and a high quality stereo to listen to music, so casting is where it's at for us (navidrome is on a raspberry pi).
