### ISSUE TITLE
App crashes in "Library" on "Albums" tab when using with navidrome

### ISSUE THREAD

**Issue by K0SS4** [austinried/subtracks#135]
**Describe the bug**
When I want to scroll my album list and the cover arts are not cached yet the app crashes(puts me back to home screen).

**To Reproduce**
1. Use the navidrome's demo server
2. Go to Library->Albums
3. Scroll down and up a little bit
4. Wait for images to load
5. See error

**Expected behavior**
The app loads cover arts(if it can't for some reason it uses a placeholder image stored locally) and doesn't crash

**Smartphone (please complete the following information):**
 - Device: Oppo Reno 4Z 5G
 - OS: Android 11/ColorOS 11.1
 - Subtracks version 1.3.0(downloaded from f-droid)

**Comment by izyspania** [comment]
You should take a look at this: https://github.com/austinried/subtracks/issues/119

**Comment by K0SS4** [comment]
Yeah it's the same problem. Closing the issue. Thanks :)
