### ISSUE TITLE
is there a tutorial on how to get in

### ISSUE THREAD

**Issue by MrConqueror** [austinried/subtracks#138]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 4]
 - OS: [e.g. Android 12]
 - Subtracks version [e.g. 1.2.0]

**Additional context**
![Screenshot_2022-07-16-16-20-01-77_4592e5f2f8541e3cde5ab7e93a41cf59](https://user-images.githubusercontent.com/102837820/179346928-8e88642c-223b-40bf-9bfa-81e2ba055cee.jpg)
Yow what is this? what to fill?

**Comment by A-Emile** [comment]
You need a subsonic api compatible music server
