### ISSUE TITLE
Does subtracks offer personalised music?

### ISSUE THREAD

**Issue by Raj2032** [austinried/subtracks#146]
Hi, I wanted to know if subtracks offers personalised music based on the music that I have listened to? Like how Spotify does it but it does it locally on the app?

**Comment by austinried** [comment]
Not really, there isn't an algorithm of any kind running to determine what would be good to recommend, and no central server the app talks to (it only talks to your server that has your own personal music collection) to get music recommendations.

**Comment by Raj2032** [comment]
@austinried Thanks for letting me know, as a suggestion I would suggest if the feature was implemented within the app though?
