### ISSUE TITLE
Chinese translation cannot be displayed

### ISSUE THREAD

**Issue by ddaodan** [austinried/subtracks#148]
**Describe the bug**
Chinese translation cannot be displayed

**To Reproduce**

**Expected behavior**
Show Chinese

**Screenshots**
![Screenshot_20221019-033156_Trebuchet~2](https://user-images.githubusercontent.com/40017293/196526508-67dc8c78-4fbc-49e8-954a-5619130d1d68.png)

**Smartphone (please complete the following information):**
 - Device: Mi 8 Pro
 - OS: Android 12
 - Subtracks version 1.3.0

**Additional context**
Rename `zh-Hans.json` to`zh.json` to fix

**Comment by wyx-666** [comment]
你好，你的Subtracks软件是怎么显示中文的呢，软件没有设置中文的选项，至少我还没找到，是自己编译的软件吗？

**Comment by wyx-666** [comment]
> **** 描述中文翻译无法显示的**bug**
> 
> **重现** 重现行为的步骤：
> 
> 1. 去 '...'
> 2. 点击 '....'
> 3. 向下滚动到“....”
> 4. 查看错误
> 
> **预期行为** 显示中文
> 
> **截图** ![Screenshot_20221019-033156_Trebuchet~2](https://user-images.githubusercontent.com/40017293/196526508-67dc8c78-4fbc-49e8-954a-5619130d1d68.png)
> 
> **智能手机（请填写以下信息）：**
> 
> * 设备：小米 8 Pro
> * 操作系统：Android 12
> * 子轨道版本 1.3.0
> 
> **附加上下文** 重命名`zh-Hans.json`为`zh.json`修复
你好，你的Subtracks软件是怎么显示中文的呢，软件没有设置中文的选项，至于我还没有找到，是自己编译的软件吗？

**Comment by austinried** [comment]
The application does not have its own option to change language, it relies on using the language you've chosen in the Android system settings.

> Rename `zh-Hans.json` to `zh.json` to fix

I noticed an issue related to this actually with the latest alpha also, and ended up having to rename this language file there to remove the script tag. If you're able to, could you try the alpha and let me know if it resolves the issue?

https://github.com/austinried/subtracks/releases/tag/v2.0.0-alpha.1

**Comment by ddaodan** [comment]
@austinried Yes, it now displays correctly
![Screenshot_20230428-165542_Trebuchet](https://user-images.githubusercontent.com/40017293/235103025-83b09153-36dc-4be8-b1e9-814e107b4db2.png)
