### ISSUE TITLE
Can't connect to my password-less profile

### ISSUE THREAD

**Issue by AlexKalopsia** [austinried/subtracks#153]
My Jellyfin profile has the password disabled, and this makes it impossible for me to use subtracks. The app - in facts - grays out `Test Connection` and `Save` if the password field is empty. 

If you point me to the right direction and it's not too complicated I can consider doing a PR myself. 

Taking a look at the code, it seems like it might just be a matter of skipping `!!password` on line `48` of `ServerView.tsx`. At the same time I am not sure if that is in line with everything else in the validation process, so I'll wait for some input first.

**Comment by austinried** [comment]
A password is required with the subsonic API and subtracks doesn't support Jellyfin at the moment, so this is expected. I'm hoping to support more servers in the future though!
