### ISSUE TITLE
Mark played track as "played"

### ISSUE THREAD

**Issue by christoschronopoulos** [austinried/subtracks#155]
@austinried thanks so much for your efforts! The app is great and plays nicely my Nextcloud music! When it comes to audio books though it is tricky to keep track of what is played and what's not after closing the app. Therefore, I would like to ask if a "played" status icon (or similar) could be added to the app.

**Comment by austinried** [comment]
Not really something that is possible with the subsonic API unfortunately. There is some support in the API for podcast tracking, but podcasts and audiobooks are outside the scope of the app here, for now I'm trying to keep this to music.
