### ISSUE TITLE
Now Playing when opening app

### ISSUE THREAD

**Issue by masterkrieger** [austinried/subtracks#156]
**Is your feature request related to a problem? Please describe.**
I can't seem to find a Now Playing section where I can pick back up the song list I was playing before I closed the app. Does it cache the currently playing list of songs?

**Describe the solution you'd like**
If I start a playlist, it would be nice to come back to the song or the place in the song I left if I had closed the app previously and continue the list of songs I was listening.

**Comment by christoschronopoulos** [comment]
+1 nice enhancement!

**Comment by austinried** [comment]
It didn't save the queue before but this is in v2.0.0-alpha.1!
