### ISSUE TITLE
Subtracks alpha.1-2.0.0 language problem

### ISSUE THREAD

**Issue by Virtuo1** [austinried/subtracks#160]
**Describe the bug**
The app is in wrong language. 

**To Reproduce**
1. Download apk and install it
2. Open app

**Expected behavior**
The app should be in either english or swedish (system language).

**Screenshots**
![Screenshot_2023-04-28-14-11-15-47_8364df8e84bc6cb6f31c661dbaeaaf78.jpg](https://user-images.githubusercontent.com/37273266/235144447-3037e05f-18f2-4f7a-b996-d4ef1db2d58a.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord
 - OS: Android 12
 - Subtracks version alpha.1-2.0.0

**Comment by austinried** [comment]
Do you have Arabic in your system languages? The app should be falling back through your list of preferred languages until it finds one that both it supports and is in your list of languages, falling back to English after that.

**Comment by Virtuo1** [comment]
I do not. I only have swedish installed, and it is set to default.
![Screenshot_2023-04-28-14-28-25-95_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://user-images.githubusercontent.com/37273266/235147430-8b4eddda-d633-4bf3-939d-068f431948ef.jpg)

Looks like this

**Comment by austinried** [comment]
Yep you're correct, looks like it's actually falling back to the first language in the list alphabetically by mistake instead of to `en`. I'll have the fix for that in alpha.2
