### ISSUE TITLE
Offline mode switch doesn't work

### ISSUE THREAD

**Issue by Marco-9456** [austinried/subtracks#162]
**Describe the bug**
The offline mode cannot be toggled on.

**To Reproduce**
Click on the offline mode switch.

**Expected behavior**
To toggle the offline mode on.

**Screenshots**

https://linksharing.samsungcloud.com/9MbbDDpe9jLo

**Device**
 - Model: [Samsung Galaxy S21+]
 - OS: [Android 13]
 - Subtracks version [2.0.0-alpha.1]

**Server**
 - Software: [N/A]
 - Version: [N/A]

**Comment by austinried** [comment]
In this case it's normal, offline mode only does anything after there is a source added. This should be made clearer though once I add a first-time setup flow.

**Comment by Marco-9456** [comment]
> In this case it's normal, offline mode only does anything after there is a source added. This should be made clearer though once I add a first-time setup flow.

Thanks for the info, I thought it will make it act like other Music Players that play locally saved audio files.

**Comment by austinried** [comment]
It should, and right now it sort of does that (when enabled it filters all lists to only show locally saved items), but it only really has any meaning if you have added a source first so that there could be downloaded files from that source.

**Comment by Y0uBetterCat** [comment]
Hi sorry i dont quiet understand, i have the same "issue" where the download button is grey and i cant press it, i dont quite understand on how to fix it, i have a navidrome server it has files i can see and listen to the music, but i cant download it, do i have to enable something first or why is that
