### ISSUE TITLE
Visualization type selector not working on main view

### ISSUE THREAD

**Issue by tetebueno** [austinried/subtracks#163]
**Describe the bug**
Some buttons to change the layout of albums to be shown are not responding.

**To Reproduce**
1. Open the app.
2. Tap on the sort/filter button in the bottom right corner.
3. Select other visualization types.
4. Nothing happens.

**Expected behavior**
Visualization should follow selection.

**Screenshots**
![photo1682707285](https://user-images.githubusercontent.com/9064236/235244087-4dae5056-c3de-4b27-92c6-4fade3901977.jpeg)

**Device**
 - Model: Moto G8 Power
 - OS: Android 11
 - Subtracks version: 2.0.0-alpha

**Server**
 - Software: Navidrome
 - Version: 0.49.3

**Additional context**
N/A

**Comment by tetebueno** [comment]
Didn't seem to be worth opening another issue, but using tha "radio" button to shuffle all songs opens the player and the playlist button doesn't seem to work:

![Screenshot_20230505-091256-965](https://user-images.githubusercontent.com/9064236/236455531-e3d2d81c-00bf-4948-b11a-f420717f8192.png)

Maybe is intended for shuffle all mode, but, if that's the case, maybe it's be worth it to gray the button out.

**Comment by austinried** [comment]
The display type buttons on the list views are just not implemented yet for this alpha, I will get them working before the beta though. Same for the button on the Now Playing screen, except that one's actually going to show the current now playing queue.

The one on the top right of the list view is a quick "clear filters" button, and only becomes enabled when you have filters selected below in that menu.

**Comment by tetebueno** [comment]
Awesome. Closing issue since everything is covered.

Bu the way, awesome work, thanks. I'm using the alpha version on a day to day basis and it works justo fine (it looks slick).
