### ISSUE TITLE
can't add source

### ISSUE THREAD

**Issue by ElRoberto538** [austinried/subtracks#171]
Hi, Thanks for releasing the new version! 

I've installed alpha 1 and 2, but when I attempt to add my navidrome server as a source the save button does nothing - a small loading spinner appears on the save button for a fraction of a second then nothing else happens. Going back to the main screen shows no sources.

The original app connects to the same server fine.

**Comment by austinried** [comment]
Can you update your issue here with your navidrome server version?

Right now I don't have proper logging implemented in the alpha so it's a little hard to troubleshoot these kinds of issues, I'm going to prioritize that next.

**Comment by ElRoberto538** [comment]
Hi, thanks. Yes I'll get that, and I'll also check the server logs and see if there's anything useful there. Just need to get my server back up after some hardware upgrades.

**Comment by ElRoberto538** [comment]
Ok, my fault, I put the wrong URL in when testing - that's what I get for not using a subdomain for Navidrome.

I love the new home/music page view!
