### ISSUE TITLE
[Feature] View/Play Recently Added Tracks

### ISSUE THREAD

**Issue by IceWreck** [austinried/subtracks#19]
Hey, thanks for making this. It looks so much more modern than D-sub and its forks. Just discovered it on f-droid.

I'm wondering if you could add an option to view and play recently added tracks.

**Comment by austinried** [comment]
Glad you like it!  This feature will be coming with the customizable home screen, you'll be able to add a number of other categories there (basically a bunch of queries that the subsonic API already supports) including recently added.  So for now, I'll close this one for #4 if that sounds good.
