### ISSUE TITLE
Navidrome - recent plays not updated

### ISSUE THREAD

**Issue by nobbysheep** [austinried/subtracks#24]
As per screenshots attached the recent plays are not being reflected in the app
![Screenshot_20210920-183726](https://user-images.githubusercontent.com/81171320/134048407-76b2ad45-7c78-454c-8657-1b57d930283c.png)
![Screenshot_20210920-183715](https://user-images.githubusercontent.com/81171320/134048415-4e7b20b0-15ab-45e8-9420-3cc1c8327a31.png)

**Comment by austinried** [comment]
For navidrome you need to enable the scrobble option in settings for it to log your plays, see here for more info: https://github.com/navidrome/navidrome/issues/593
