### ISSUE TITLE
[Bug] Playback screen with an aspect ratio > 16:9 

### ISSUE THREAD

**Issue by ghost** [austinried/subtracks#28]
The playback screen has a blank area at the bottom on screens with aspect ratios larger than 16:9.
Example, with an aspect ratio of 18.7:9:
![Screen](https://user-images.githubusercontent.com/88929509/136967606-7558b9e4-fb7b-4429-a808-a50c6ac1113e.png)

**Comment by danog** [comment]
+1, same issue bere.

**Comment by austinried** [comment]
Fixed in #76
