### ISSUE TITLE
[Bug] Notification keeps coming back

### ISSUE THREAD

**Issue by erickhavel** [austinried/subtracks#31]
Even though I swipe away the notification (of the last played song, with playback controls) it keeps coming back after a (random?) while.

Moto G8 Plus / Android 11

**Comment by austinried** [comment]
Do you have the option enabled to "pin" the media player (it's called that in 12, something similar in 11) in Android? If you long press on the notification you should get a settings option to see if this is enabled, it's an Android option that keeps all media player notifications around longer than they should.

**Comment by erickhavel** [comment]
Nothing happens when I long-press. I can swipe (left or right), get a settings cog, which takes me to a "Media" setting screen with the option "Hide players when the media session has ended", which is enabled. It has a description "The player allows you to resume a session from the expanded Quick Settings panel.

**Comment by austinried** [comment]
Should be "resolved" in v2.0.0-alpha.1, with the caveat that Android sort of handles this outside of the app's control for media players these days.
