### ISSUE TITLE
[BUG] Playback resumes after phone call ends.

### ISSUE THREAD

**Issue by vacuumbeef** [austinried/subtracks#33]
When I end a phonecall music starts playing, even if it was stopped before.

One plus 6t, Android 11.

**Comment by dwkra** [comment]
I have this problem too. Will also happen when I stop watching a video on a webpage, Subtracks will start playing music.

If I press the stop button from the full pull-down settings Subtracks will disappear and not play on its own, but having to stop my music all the time is not behavior I'm used to navigating with any other media app I use.

**Comment by austinried** [comment]
I haven't been able to repro this yet but I think I can see where it's happening, so I'm gonna keep trying to run some tests on different setups before I put out the fix.

**Comment by austinried** [comment]
Alright, I've been able to repro and fix this finally! Turned out to be the the ducking issue I thought it was and indeed the same thing that's causing #32.  I'll have the fixed merged in soon and hopefully start the push out to google play/f-droid today.
