### ISSUE TITLE
unsolicited requests

### ISSUE THREAD

**Issue by kusky3** [austinried/subtracks#34]
i installed the latest version from fdroid
when started, the app makes 2 unsolicited requests to:
10.0.2.2:8082
10.0.3.2:8082

but the server is set to 192.168.1.*
Why?

**Comment by austinried** [comment]
So I did some tcpdump captures to see what this was, and as far as I can tell this is intended behavior from a React Native app.  If you're running the app in an emulator, this address appears to be the host machine and it's looking to see if there's a react-native server running on the host to do its normal development stuff (downloading the js files, logging, etc.)  If you're running on a real device though these requests don't go anywhere and nothing happens.
