### ISSUE TITLE
[bug] gradient makes text unreadable

### ISSUE THREAD

**Issue by mariorossi77** [austinried/subtracks#36]
![e0867995-9c38-4bbc-b1f1-909694e6a215](https://user-images.githubusercontent.com/37901668/140481868-0bb6f9af-7f12-47dc-a775-d7c4a14748b6.jpg)

some gradients shouldnt be allowed because text has no contrast

**Comment by austinried** [comment]
Should be fixed in 2.0.0 with new font colors
