### ISSUE TITLE
[Bug] Search only shows title instead of albums

### ISSUE THREAD

**Issue by eRaz3r** [austinried/subtracks#39]
Unfortunately, it is not possible to search for albums, only titles are displayed. Can I change this?

**Comment by austinried** [comment]
Could you elaborate on this? Currently search works for me for albums, songs, and artists.  What subsonic server are you using?

**Comment by kusky3** [comment]
tested with navidrome and gonic servers and the search function works with albums

**Comment by eRaz3r** [comment]
Don't know what i've done wrong, now everything seems to be okay and subtracks is now showing the albums also.
