### ISSUE TITLE
Cannot download media from my server

### ISSUE THREAD

**Issue by f-gdovin** [austinried/subtracks#41]
I noticed that download button is disabled and there seems to be no way of enabling it on my Poco X3 Pro (Android 11). I suspect this to be permission issue, when the app does not have permission to access media and does not ask for it.

See the screenshots below.

Server is Navidrome running within my LAN and I am able to download media from it using other *Sonic apps, such as substreamer.

![Screenshot_2021-11-27-09-00-17-454_com subtracks](https://user-images.githubusercontent.com/10159330/143673415-b7c48cbd-6aeb-4159-89a4-8ccacbf9f468.jpg)

![IMG_20211127_090302](https://user-images.githubusercontent.com/10159330/143673429-4b1d92a5-0180-44bb-84e4-8cbffd85c4bf.jpg)

**Comment by austinried** [comment]
This is actually just my bad UX choices, downloading tracks is just not implemented yet so I disabled the button.  Same thing with the cast button, I should probably just remove these until the feature is actually there.
