### ISSUE TITLE
Any reason that, despite being a React Native app, there is no iOS support?

### ISSUE THREAD

**Issue by radiosilence** [austinried/subtracks#43]

**Comment by austinried** [comment]
I don't own any Apple devices, so it would be pretty tough for me to maintain an iOS release.

**Comment by tuandinh0801** [comment]
Really impressed with the app, it would be great if there is an ios version.
Do you guy welcome ios support PR?

**Comment by austinried** [comment]
Thanks, I appreciate it but at the moment for iOS support I would either need to get the equipment myself or have someone I could rely on to be a maintainer for the iOS version.
