### ISSUE TITLE
Starred is not working

### ISSUE THREAD

**Issue by DOFfactory** [austinried/subtracks#49]
Using LMS as a subsonic server (https://github.com/epoupon/lms) with DSub. I tried to give Subtracks a go, all works fine, however, the starred songs do not show correctly. Could you please fix it?

**Comment by austinried** [comment]
Just tested again and stars seem to be working with at least Subsonic and Navidrome servers, so I'm not sure what the issue could be here off-hand.  Could you elaborate on what you mean by "not showing correctly?"  Do you have starred items on the server that are not showing up in the app, or is starring them in the app not sticking?

**Comment by DOFfactory** [comment]
Hm, this is an interesting issue as I dived deeper. So what DSub does to the server is that I star individual tracks and not albums. The server (and I guess Subsonic specification) apparently distinguishes starred albums, starred artists, and starred tracks. I found starred albums and starred artists filtering, but I think the starred tracks are currently missing in Subtracks. Am I right or I am really missing something?

**Comment by austinried** [comment]
Oh I think I see what you mean now, yes currently there isn't a way in Subtracks to list only your starred tracks.  You're right that the subsonic API does differentiate between all of those types of stars, you should be able to filter albums and artists by starred in those views.  Right now I'm planning on adding a starred tracks view to the customizable home screen lists once I get those up and going.

**Comment by austinried** [comment]
Linking this into #4 so I can track it there.
