### ISSUE TITLE
Pre-cache/buffer not seconds but tracks

### ISSUE THREAD

**Issue by DOFfactory** [austinried/subtracks#50]
Would it be please possible to introduce a similar functionality as DSub, namely, not to pre-cache/buffer in seconds but tracks? It might help for some to avoid stuttering while travelling via high-speed trains and using mobile data, etc.

**Comment by austinried** [comment]
This is actually already happening in a way: the buffer is measured in seconds but it will cross track boundaries.  So for example, if you have the maximum buffer time set to 60 seconds (default), and you start to play a song that's 30 seconds long, the player should try to buffer all of the first song and also 30 seconds of the next.

I'm planning to implement more options for caching tracks though with #3 so this will get easier with that, but in the meantime you can increase that max buffer time in the settings to get a better experience with spotty connections.

**Comment by DOFfactory** [comment]
Thanks for the explanation, I am a bit hesitant towards the buffering by seconds for the following reason: my subsonic server does transcoding, and once a connection is broken on the transcoded stream, the whole song interrupts and it needs to be re-transcoded and re-streamed. Therefore, I would still introduce a buffer-by-tracks option, as this will avoid such interruptions while moving between mobile cells
