### ISSUE TITLE
Bug: End of alarm causes music to play

### ISSUE THREAD

**Issue by nep2ner** [austinried/subtracks#52]
App Version 1.1.0
Android 12

After an alarm goes off (if it runs out, is snoozed,  or canceled), Subtracks starts to play music. This only occurs if the app has been playing a song at some previous point. For example, this bug does not occur under the following two conditions: (1) The app is forced closed before the alarm goes off (2) The app is forced closed, opened, but exited right away before the alarm goes off (no music is played in the app).

However, I've observed this bug occurring when music hasn't been played on the app for 10 hours, so I'm not sure if time is much a a factor. Just state.

**Comment by austinried** [comment]
Appreciate the detailed report, but I actually just closed #32 for this and released version 1.1.1 which should have the fix.

**Comment by nep2ner** [comment]
Sorry for the duplicate and thank you for the fix!
