### ISSUE TITLE
FLAC files don't seem to natively load

### ISSUE THREAD

**Issue by zkldi** [austinried/subtracks#57]
**NOTE**: This might be an issue with Navidrome. I'm going to file something similar there, I think!

Some of the albums on my server are in FLAC. When I try to load them, they just load for a while and eventually time out. I fixed this by configuring navidrome to use MP3 encoding, but should FLAC be natively supported?

Not sure whether I'm doing something wrong or not here! Thanks for the client by the way, it looks really good.

**Comment by dwkra** [comment]
I am also going from Navidrome (Docker image on RPi) to SubTracks. The vast majority of my files are FLAC and I've only had issues with my streams when my signal is weak. I don't think I've ever had issues when on 5G, and have never had issues on WiFi.

**Comment by zkldi** [comment]
Interesting. I'm running on a debian 11 box under docker, so we should be having the same navidrome server experience. I'll try and find the conditions that cause it now.

**Comment by edenist** [comment]
I'm running navidrome in a freebsd jail [recently migrated from airsonic], and I don't have any issues with my FLAC library on subtracks on wifi or 4G. 

That said, I do recall having some issues a while back with FLAC playback with ultrasonic + airsonic, which ended up being ultrasonic not explicitly setting default max bitrate values and the airsonic transcoding system getting confused. 

All that is to say, in my experience communication of transcoding preferences can be temperamental. I would recommend trying out the max bitrate settings in subtracks and making sure navidrome behaves as expected to see if transcoding is configured correctly [and that is accurately detects to do *no* transcoding when bitrate is set to unlimited in subtracks].

**Comment by austinried** [comment]
I've also got a few FLAC albums in my library using navidrome as well and haven't had issues with them when the transcoding is set to unlimited (none), so this does sound a bit odd. Maybe it has something to do with how your files are encoded specifically?  Also, do you know if these files play (without transcoding) in other Android subsonic clients?

Behind the scenes subtracks is using ExoPlayer for audio playback, which should be able to play back everything that Android natively supports (which does include FLAC since 3.1: https://developer.android.com/guide/topics/media/media-formats).

**Comment by zkldi** [comment]
> I've also got a few FLAC albums in my library using navidrome as well and haven't had issues with them when the transcoding is set to unlimited (none), so this does sound a bit odd. Maybe it has something to do with how your files are encoded specifically? Also, do you know if these files play (without transcoding) in other Android subsonic clients?

The tracks in question are working fine on DSub. I'll try and isolate a FLAC with the issue today and send it over.

**Comment by austinried** [comment]
Closing this for now but feel free to post the track if it's still an issue and we can check it out.
