### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by mill1000** [austinried/subtracks#58]
Hi,

I'm interested in trying to do some development for this project, but I'm rather new to React Native. Could you write up some basic documentation on building the project?

I've done my best to follow the React Native documentation on setting up an environment. Everything worked out OK once I switched to `yarn` over `npm`.

Currently builds are failing due to a signing issues.
```
Task :app:validateSigningRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file not set for signing config release
```
 I thought I could get around this by performing a debug build but `--varient=debug` didn't seem to do the trick.

**Comment by austinried** [comment]
Yeah I should have gotten around to this sooner but I'm working on it now in conjunction with some dependency updates.  Hopefully will have that up soon.

In the meantime, it sounds like you may be doing something out of order and it's looking for a keystore for signing that doesn't exist.  Currently both debug and release builds should be set to use the debug keystore file (release via the `-PsignReleaseWithDebug=true` option).  Are you trying to run gradle by itself?

The (very) shortened version of the build steps I use is `yarn` to install packages, `scripts/prepare-exoplayer-ffmpeg.sh` to build the ffmpeg ExoPlayer dependency, and then either `yarn start` with `yarn android` to run Metro and build debug or just `yarn android:release` to build release.

**Comment by izyspania** [comment]
jcenter() is down , the workaround for me was:

        google()
      //  jcenter()
        mavenLocal()
        mavenCentral()
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
        maven { url "https://repo.spring.io/plugins-release/" }

**Comment by mill1000** [comment]
Cool. Thanks, I was able to get a build working. Not sure what I had got wrong last time but I probably had a broken environment or something.

**Comment by mill1000** [comment]
FYI here are the steps I followed with a clean WSL2 install of Ubuntu 20.04

# Prerequisites
```
sudo apt-get install unzip git build-essential automake
```

# Install NodeJS 16 from NodeSource
```
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs
```

# Install yarn
These instructions came from NodeSource as well.
```
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
```

# Install JDK
```
sudo apt-get install default-jdk
```

# Install Android SDK manually via command line tools
You could also use Android Studio.

## Get command line tools
```
wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
unzip commandlinetools-linux-7583922_latest.zip

mkdir -p ~/android-sdk/cmdline-tools
mv cmdline-tools ~/android-sdk/cmdline-tools/latest
```

## Setup environment
```
export ANDROID_HOME=$HOME/android-sdk
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
```

## Install platform-tools
```
sdkmanager "platform-tools" 
```

# Clone subtracks
```
git clone https://github.com/austinried/subtracks.git
cd subtracks
git submodule init
git submodule update
```

# Get packages
```
yarn
```

# Build subtracks prerequisites
```
cd scripts
./prepare-exoplayer-ffmpeg.sh
```

# Build
In one terminal
```
yarn start
```

In another terminal
```
yarn android
```

**Comment by oyr5611** [comment]
I am not the one who asked the question, but thanks to the above answer, I am able to debug.
Thank you very much for the detailed explanation.

**Comment by austinried** [comment]
Build instructions have been added here: https://github.com/austinried/subtracks/blob/master/BUILDING.md
