### ISSUE TITLE
[Feature] ListenBrainz support

### ISSUE THREAD

**Issue by retiolus** [austinried/subtracks#63]
Keep tracks of what music you listen thanks to ListenBrainz: https://listenbrainz.org/

**Comment by edenist** [comment]
Isn't this generally configured on the server side? 

With both airsonic and navidrome, scrobbling is setup in your account. I was under the impression that the client just tells the server whether to scrobble plays or not. Navidrome allows scrobbling to last.fm and listenbrainz.

**Comment by austinried** [comment]
That's correct, scrobbling is already supported in subtracks, you'd have to configure your server to tell it where that scrobble goes (last.fm, listenbrainz, etc.).
