### ISSUE TITLE
[Features] audiobooks focused

### ISSUE THREAD

**Issue by izyspania** [austinried/subtracks#64]
UPDATED the post.
- Variable playback speed
- Sleep timer (stop playing after X amount of time)
- Keep screen on option.
- Next track / Last track buttons when player is minimized 
- Go forward / backwards for the current track by X seconds (buttons in the player view)
- Continue where you left on different device (Show a pop up screen when you login in the app asking if you want to start from where u stopped.
-  Bookmarks section in a menu with option to delete bookmarks from the list as well of adding bookmarks from the player screen.
- Add Genre section to Library screen instead of sorting , similar to artists/playlist sections
- Starred section moved/added in a separate menu.
- Artists / Album description. 
- Star rating option (5 star) for albums ( maybe showing the stars over album cover ) 
- Chrome Cast for audio
- Android auto

**Comment by izyspania** [comment]
Some info if it helps things speed up: (so you dont have to research , probably you already knew them but just in case)

Variable playback speed
i think is supported by exoplayer

Continue where you left on different device? (or on same device for later):
http://your-server/rest/getPlayQueue
http://your-server/rest/savePlayQueue

Bookmarks API:
http://your-server/rest/getBookmarks
http://your-server/rest/createBookmark
http://your-server/rest/deleteBookmark

Chromecast:
https://github.com/react-native-google-cast/react-native-google-cast

**Comment by austinried** [comment]
Thank you for all this info, I hadn't planned on implementing any audiobook-specific support but I am considering it down the line now once other major features are done so I'll leave this open so I can come back to it.

You mentioned some other issues here as well with username/password errors, could you open separate issues for those if they are still a problem?

**Comment by izyspania** [comment]
Thanks , some of the features are not audiobook specific and could be great to have them even for music. (and the more audiobooks specific features they dont have to be branded audiobook specific just as features that you can use if you want to , like in other subsonic apps , DSUB etc.)

The username/password errors are not really errors just more as a preference , if you add your server with wrong user/pass (and you dont test it to see everything is OK before saving it) then would be nice a notice while u browsing the app that says for example "your username or password is incorrect" rather than just blank page but its not really needed.

**Comment by kusky3** [comment]
there's an alternative for that
https://github.com/PaulWoitaschek/Voice
just saying

**Comment by izyspania** [comment]
Thanks for the info , i just like your app more:)

**Comment by austinried** [comment]
Thanks for this, for now I've decided to keep focus on music and will not be doing audiobook/podcast features.
