### ISSUE TITLE
Connecting to SSL enabled Subtracks

### ISSUE THREAD

**Issue by Btrc4t** [austinried/subtracks#65]
I've setup a nginx redirection which enables https connections to a self-hosted subsonic server. The SSL certificate is self signed. Attempting a connection to the HTTPS version of the subsonic server with subtracks fails. 

Is it possible for the application to accept https connections and maybe even self-signed certificates optionally? I've checked with the self-signed certificate added to the trust store of the android device, that did not result in a successful connection - however in the browser it's recognized as a secure connection after that step.

**Comment by Btrc4t** [comment]
[This is the line](https://github.com/austinried/subtracks/blob/6883a556bf635788c23a20520c83b086de31cd85/app/screens/ServerView.tsx#L176) where this issue comes from, it assumes that a Subsonic (or similar) server can only be http.

**Comment by austinried** [comment]
Support for self-signed certificates was added in #17 already, so this should be working.  It sounds like you are missing a step here though, which is that in order for Android to trust a self-signed certificate, you need to add the CA (certificate authority) cert to the user trust store, and then sign your own certificate with that CA.
