### ISSUE TITLE
Stops playing

### ISSUE THREAD

**Issue by rightsaidfred99** [austinried/subtracks#66]
Just noticed when in the car and connected to BlueTooth.

If I press skip track once, Subtracks will play next song. 
However if press more than once, a few times, I find that Subtracks will skip forward but will not actually play the track.

While driving, I have to turn the screen on and press play via the notification.

**Comment by austinried** [comment]
I haven't been able to duplicate this, can you tell me if it happens only when you press next on your bluetooth device or on the notification/in the app's Now Playing screen as well?  Also, what subsonic server are you using and could you check the logs there to see if there are any errors reported from the time period where this happened?

**Comment by rightsaidfred99** [comment]
When I press next on the bluetooth device (ie steering wheel of car) it just displays the song name on the card='s HUD
The now playing song on Subtracks is correct too, but it forgets to play


I'm using Navidrome to stream. I can't find any error logs. 

It seems if I press play on the lockscreen of the phone again it works. 

I will try to find a way to replicate this 100%!

I was using Gelli as a player and Jellyfin before and this didn't happen so can rule out the car and or phone in this regards perhaps.

**Comment by rightsaidfred99** [comment]
How do I find logs? 

I've discovered Subtracks stops playing after two or three songs on Android. 

I've set the battery to unrestricted but the issue remains that (on my end), the player will not play more than 2 songs consecutively. :(

**Comment by austinried** [comment]
There are no logs currently, though I'm thinking about adding some now.  I have experienced this now very rarely on my phone, but not on an emulator yet where I can see debug logs.  Going to try this on a couple other phones soon though to see if I can get a better repro.
