### ISSUE TITLE
No music displayed with "ok" Connection to Ampache/Subsonic server

### ISSUE THREAD

**Issue by suilujjulius** [austinried/subtracks#69]
Hi Austin (and all of you assisting!),
First of all compliments for the well-organized and beautiful interface, it's something I've been looking forward to. I'm running an Ampache server that allows subsonic streaming. When testing the connection, I tried it both locally and via a ddns address, I get a confirmation that the connection is "ok". 
But afterwards I won't see any tracks nor can I search for them. Both plain text and token + salt behave exactly the same.
The strange thing is that with other apps, such as subsonic and ultrasonic, I can access my server and play my music. 
I was wondering whether subtracks requires a specific setting on the server side or of I'm missing anything else.
Thanks a lot for your help.

Versions
Ampache 3.9
Android 12
Subtracks 1.1.1

Regards, Julius

**Comment by austinried** [comment]
Is your music library organized by tags or by folder?  Subtracks does not currently support the subsonic API's "by folder" endpoints.

**Comment by suilujjulius** [comment]
Hi Austin,
Thanks for your answer. On the backend/server everything is organized in folders but on Ampache (my Subsonic client) everything is sorted by tags. So am I out of luck at this time?
Cheers, Julius

**Comment by austinried** [comment]
I'm not too familiar with Ampache but it sounds like that should be working then. If you can use another client like DSub for example with the "browse by tags" option enabled, then it should work here too.

So now I'm wondering if there's something weird about the responses that Ampache is sending, you don't happen to see anything in Ampache's logs that might help us here do you?

**Comment by suilujjulius** [comment]
Hi Austin, 
thanks for your answer. I did both checks. 

1. DSub is working fine with the "Browse by tags" option enabled
2. I enabled the logging in Ampache and get the following error message, apparently the SubSonic client isn't compatible. 

`2022-04-08 14:35:19 [admin] (subsonic) -> Requested client version is not supported 
2022-04-08 14:35:19 [ampache] (PHP) -> [Runtime Error] SimpleXMLElement::addAttribute(): Attribute already exists in file /share/CACHEDEV1_DATA/.qpkg/Ampache/Ampache/lib/class/subsonic_xml_data.class.php(198) `

I checked in the file subsonic_xml_data.class.php and apparently the API version is 1.11.0.

Does this help?

Regards, Julius

**Comment by austinried** [comment]
That does help, currently the lowest subsonic API version subtracks supports is 1.13.0.  Ampache appears to be using a version that's about 7-ish years out of date.

Last I had checked 1.12.0 was missing an endpoint that I use, which is why I stopped going backwards at 1.13.0 for now, but I would like to support those older versions in the future.  I'm working on refactoring how the app does querying to the API right now, so hopefully once that's done it will be easier to support those.

**Comment by austinried** [comment]
Actually I'm looking back on previous issues about this now and realizing that the move to 1.13.0 was specifically for ampache, is your version perhaps out of date?  There's some discussion here about it in #42 and also over in ampache's repo here: https://github.com/ampache/ampache/issues/2494#issuecomment-990388520

**Comment by suilujjulius** [comment]
Ok, thanks for the information. It´s actually not Ampache´s fault but my servers/mine. I´m using an old version of Ampache (3.9) as my server isn´t supporting newer versions of Ampache (now 5.2.1). I'll have a look whether I manage to update it.
I learned something today, thanks for that!

**Comment by suilujjulius** [comment]
I forgot to close the issue, the root cause is identified and clear.
