### ISSUE TITLE
Does not list anything from selected artist

### ISSUE THREAD

**Issue by greenfuse** [austinried/subtracks#72]
Subtracks fails to list anything when an artist is selected. The issue is consistent when selecting either from the artists listed in the library or in a search result. It indefinitely displays a spinning icon. 

Subtracks will successfully display and play tracks from albums and playlists and it also finds and plays individual songs from a search. It just fails when selecting the artist.

Environments:
Over 4000 music files in over 340 folders/albums hosted on Nextcloud version 23.0.0 Music app version 1.50
Subtracks version 1.1.1 on Android 11

**Comment by litLizard69** [comment]
This was fixed in the last update. It works now!

**Comment by austinried** [comment]
Glad to hear that, I made some background updates to the way requests for data/caching is handling so that must have done it!
