### ISSUE TITLE
can't connect to airsonic hosted via subfolder

### ISSUE THREAD

**Issue by zwnk** [austinried/subtracks#73]
Hit there,
I'm trying to use subtrack with an airsonic server hosted like this:
`http://IP: Port/airsonic` and `http://domain.com/airsonic` and both won't work but no specific error given.

**Comment by thrOo** [comment]
Hi,
i had the same issue with navidrome. There is an enviroment varible for a baseurl i needed to enter for navidrome change the url to when appending querys or linking to stuff (it defaults to the root domain).
After adding the baseurl it worked.
running and connecting successfullyto  two instances
`http://domain.com/music`, `http://domain.com/audiobooks`

Does airsonic have an ui at http://domain.com/airsonic ? is it working and can you navigate around?

Hope it helps

**Comment by zwnk** [comment]
my airsonic works fine on a my hosted path. also other players like ultrasonic work fine with it. 
subtracks does not wan't to connect to my server.

**Comment by austinried** [comment]
What kind of rewriting of the URL are you doing in your reverse proxy?  When subtracks sends a request to the server, it uses this format:
```javascript
`${this.address}/rest/${method}.view?${urlParams}`
```

So requests in your case should be going to `http://domain.com/airsonic/rest/ping.view?u=username&p=password&v=1.13.0&c=subtracks`, as an example.  You say this works with other clients, do you know what full URL ends up being used by those clients that does work?

**Comment by zwnk** [comment]
so this weekend i had the time to test the latest version and its working now.
