### ISSUE TITLE
Track numbers

### ISSUE THREAD

**Issue by zelleb** [austinried/subtracks#74]
Cool player!

Could you add track numbers to album view and maybe queue too?

![signal-2022-02-15-23-59-06-635](https://user-images.githubusercontent.com/19358704/154164147-391e3eca-2f8f-4856-ab8f-bffb8b11a28a.jpg)

**Comment by austinried** [comment]
I'll add disc number/grouping here eventually but I don't think there's room for track numbers, considering the download and (conditional) multiselect UI I'll be adding in the future as well.  They also don't seem that useful to me, compared to the other info that could be there anyway.
