### ISSUE TITLE
Doesn't scale properly on pixel 4a

### ISSUE THREAD

**Issue by AliceGrey** [austinried/subtracks#83]
Several parts of the GUI hide underneath the top banner.

![Screenshot_20220330-193540.png](https://user-images.githubusercontent.com/8949059/160953400-6e2f028e-4051-4679-8e77-4f185d6ca389.png)

![Screenshot_20220330-193943.png](https://user-images.githubusercontent.com/8949059/160953458-5e167d92-4360-402b-82a5-237eb9de3e89.png)

**Comment by austinried** [comment]
That's really strange, I'm running it in an emulator for the PIxel 4a and I don't see this issue.  It's almost like it thinks the app is in fullscreen mode, does the status bar at the top ever disappear?

**Comment by haeringer** [comment]
I can reproduce this on my Pixel 4a. The status bar at the top does not disappear.

**Comment by austinried** [comment]
Just updated my emulator and I can see it now as well, looks like an Android update broke this.  Will look into that

**Comment by austinried** [comment]
As far as I can tell, the Android 12.1 update causes this issue on at least the Pixel 4a, and maybe other Pixel devices as well.  The issue stems from an incorrect value reported by react native from `StatusBar.currentHeight`, which on the 4a used to report the correct value (49.45454406738281) and now reports what looks like a default (24).

Anyway, seems like react-native-safe-area-context knows how to get this value correctly so I've switched to using that for now.
