### ISSUE TITLE
Minor bug when opening player from notification bar

### ISSUE THREAD

**Issue by izyspania** [austinried/subtracks#89]
WARN  The navigation state parsed from the URL contains routes not present in the root navigator. This usually means that the linking configuration doesn't match the navigation structure. See https://reactnavigation.org/docs/5.x/configuring-links for more details on how to specify a linking configuration.

**Comment by austinried** [comment]
Yeah I think I remember trying to get this to work (open the now playing screen) and having trouble with the dynamically generated linking scheme I had gone with, haven't revisited it yet. It still opens the app and this is a debug-only warning though, I would take a PR to fix it but it's not quite a bug.
