### ISSUE TITLE
[Feature] View starred songs

### ISSUE THREAD

**Issue by stylemistake** [austinried/subtracks#95]
A way to view/play/shuffle all songs that have been starred. Could be implemented as a built-in, hardcoded playlist (I presume that would be simple to do).

This is somewhat similar to #92, but there is an API for fetching starred songs, which makes it straightforward to implement.

http://www.subsonic.org/pages/api.jsp#getStarred

**Comment by austinried** [comment]
That's true, I think I will track this in both #92 which mentions the `getStarred` method and #4 though, which are both where this is likely to be exposed (as a sort option for a Songs tab and also as a list you can add to your home screen and play from there).
