### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by clyhtsuriva** [austinried/subtracks#97]
Seeing #30, I started to contribute on Weblate to bring a French translation, and I've stumbled upon a spelling error :  

![image](https://user-images.githubusercontent.com/61652557/163339621-855c7aa1-41fc-4dc1-9573-a38890790113.png)
https://hosted.weblate.org/translate/subtracks/subtracks/en/?checksum=67829c1b75a7409f&sort_by=-priority,position

While it's written `View Arist`, I guess it should be `View Artist`

**Comment by austinried** [comment]
Thanks, fixed it!  I think I've also enabled editing for the base language now too, so feel free to fix any others you find.

**Comment by clyhtsuriva** [comment]
Nice ! Will do :)
